[package]
name = "ledgermind-storage-sqlite"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
ledgermind-application = { path = "../ledgermind-application", version = "0.1.0" }
ledgermind-domain = { path = "../ledgermind-domain", version = "0.1.0" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
